"""
Configuración de reglas operativas y horarios para el módulo de nómina.
"""

HORA_INICIO_JORNADA = "07:00"
HORA_FIN_JORNADA_L_J = "17:00"
HORA_FIN_JORNADA_VIERNES = "13:20"
MINUTOS_DEDUCCION_ALIMENTACION_L_J = 60
MINUTOS_DEDUCCION_ALIMENTACION_VIERNES = 0
MINUTOS_DEDUCCION_ALIMENTACION_SABADO = 0
